baseURL = "https://yanh.org/"
languageCode = "en-us"
title = "Yan Hui"
theme = "hugo-ink"
paginate = 5

copyright = "© Yan Hui"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-145387507-1"
disqusShortname = "yanhui"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
	subtitle = "Be true, be wild and be happy"
	author = "Yan Hui"
	description = "Yan's personal website."
	favicon = "https://icons.iconarchive.com/icons/iconka/meow/64/cat-clean-icon.png"
	
  highlightjsVersion = "10.5.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml", "bash", "python"]
  highlightjsTheme = "github"
  
  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "3.1.2"

	# Optional 64x64 avatar image.
	avatar = "https://icons.iconarchive.com/icons/iconka/meow/64/cat-clean-icon.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/yan-hui/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/yanhuii09"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/yanhui09"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
